/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Book;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class BookItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookItemPanel
     */
    public BookItemPanel() {
        initComponents();
         setPreferredSize(new Dimension(96, 146));
    }
     public void setBook(Book book) {

        if (book.getDuongDanAnh() != null && !book.getDuongDanAnh().isEmpty()) {
            try {
                File file = new File(book.getDuongDanAnh());
                if (file.exists()) {
                    BufferedImage originalImage = ImageIO.read(file);
                    Image scaledImage = originalImage.getScaledInstance(
                    58, 70, Image.SCALE_SMOOTH);
                    jtxtAnhBI.setIcon(new ImageIcon(scaledImage));
                    jtxtAnhBI.setText(""); // Xóa text nếu có ảnh
                } else {
                    jtxtAnhBI.setIcon(null);
                    jtxtAnhBI.setText("Không tìm thấy ảnh");
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                jtxtAnhBI.setIcon(null); // Xóa ảnh nếu có lỗi
                jtxtAnhBI.setText("Lỗi tải ảnh");
            }
        } else {
            jtxtAnhBI.setIcon(null);
            jtxtAnhBI.setText("Ảnh sách"); // Đặt lại text mặc định
        }
        // Update text information
        jtxtNameBI.setText("" + book.getTenSach());
        jtxtPriceBI.setText("$" + book.getGiaBan());
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtAnhBI = new javax.swing.JLabel();
        jtxtNameBI = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtxtPriceBI = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 150));

        jtxtAnhBI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtAnhBI.setText("Anh");
        jtxtAnhBI.setPreferredSize(new java.awt.Dimension(58, 70));

        jtxtNameBI.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jtxtNameBI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtNameBI.setText("Name");
        jtxtNameBI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jtxtPriceBI.setBackground(new java.awt.Color(51, 153, 255));
        jtxtPriceBI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtPriceBI.setForeground(new java.awt.Color(255, 255, 255));
        jtxtPriceBI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtPriceBI.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jtxtPriceBI, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtxtPriceBI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtxtNameBI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jtxtAnhBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtxtAnhBI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNameBI, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtxtAnhBI;
    private javax.swing.JLabel jtxtNameBI;
    private javax.swing.JLabel jtxtPriceBI;
    // End of variables declaration//GEN-END:variables
}
