/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CustomerController;
import Controller.MainMenuController;
import Model.Customer;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author MSI GF63
 */
public class CustomerM extends javax.swing.JFrame {
    private CustomerController customerController;
    private MainMenuController mainMenuController;

    /**
     * Creates new form CustomerM
     */
    public CustomerM() {
        this(null);
    }

    public CustomerM(MainMenuController mainMenuController) {
        this.mainMenuController = mainMenuController;
        initComponents();
        customerController = new CustomerController(this, mainMenuController);
        
        jTable_Customers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && jTable_Customers.getSelectedRow() != -1) {
                    displaySelectedCustomerInfo();
                }
            }
        });
        
        customerController.loadAllCustomers();
    }

    public void displayCustomers(ArrayList<Customer> customers) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_Customers.getModel();
        dtm.setRowCount(0);
        dtm.setColumnCount(0);

        dtm.addColumn("Mã KH");
        dtm.addColumn("Tên KH");
        dtm.addColumn("Số ĐT");

        for (Customer customer : customers) {
            Vector<Object> row = new Vector<>();
            row.add(customer.getMaKH());
            row.add(customer.getTenKH());
            row.add(customer.getSdt());
            dtm.addRow(row);
        }
    }

    private void displaySelectedCustomerInfo() {
        int selectedRow = jTable_Customers.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) jTable_Customers.getModel();
            jtxtMaKH.setText(model.getValueAt(selectedRow, 0).toString());
            jtxtTenKH.setText(model.getValueAt(selectedRow, 1).toString());
            jtxtSdt.setText(model.getValueAt(selectedRow, 2).toString());
        }
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    private void clearInputFields() {
        jtxtMaKH.setText("");
        jtxtTenKH.setText("");
        jtxtSdt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JPanel_Top = new javax.swing.JPanel();
        JUpper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnThem = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        JMiddle = new javax.swing.JPanel();
        JMaKH = new javax.swing.JLabel();
        JTenKH = new javax.swing.JLabel();
        jtxtMaKH = new javax.swing.JTextField();
        jtxtTenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSdt = new javax.swing.JTextField();
        JBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Customers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTimKH = new javax.swing.JTextField();
        jbtnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel_Top.setBackground(new java.awt.Color(255, 255, 255));
        JPanel_Top.setForeground(new java.awt.Color(242, 242, 242));
        JPanel_Top.setFocusTraversalPolicyProvider(true);

        JUpper.setBackground(new java.awt.Color(0, 0, 102));
        JUpper.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý khách hàng");

        jbtnThem.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12));
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnSua.setText("Sửa");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JUpperLayout = new javax.swing.GroupLayout(JUpper);
        JUpper.setLayout(JUpperLayout);
        JUpperLayout.setHorizontalGroup(
            JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JUpperLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jbtnThem)
                .addGap(18, 18, 18)
                .addComponent(jbtnSua)
                .addGap(18, 18, 18)
                .addComponent(jbtnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
        );
        JUpperLayout.setVerticalGroup(
            JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JUpperLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtnThem)
                    .addComponent(jbtnSua)
                    .addComponent(jbtnXoa)
                    .addComponent(btnBack))
                .addGap(15, 15, 15))
        );

        JPanel_Top.add(JUpper, java.awt.BorderLayout.NORTH);

        JMiddle.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        JMaKH.setText("Mã khách hàng:");
        JMiddle.add(JMaKH);

        jtxtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaKHActionPerformed(evt);
            }
        });
        JMiddle.add(jtxtMaKH);

        JTenKH.setText("Tên khách hàng:");
        JMiddle.add(JTenKH);
        JMiddle.add(jtxtTenKH);

        jLabel3.setText("Số điện thoại:");
        JMiddle.add(jLabel3);
        JMiddle.add(jtxtSdt);

        JPanel_Top.add(JMiddle, java.awt.BorderLayout.CENTER);

        getContentPane().add(JPanel_Top, java.awt.BorderLayout.NORTH);

        JBottom.setLayout(new java.awt.BorderLayout());

        jTable_Customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Số ĐT"
            }
        ));
        jScrollPane1.setViewportView(jTable_Customers);

        JBottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Tìm kiếm:");
        jPanel1.add(jLabel5);

        jtxtTimKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTimKHActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTimKH);

        jbtnTim.setText("Tìm");
        jbtnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTim);

        JBottom.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(JBottom, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaKHActionPerformed

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        String maKH = jtxtMaKH.getText();
        String tenKH = jtxtTenKH.getText();
        String sdt = jtxtSdt.getText();

        Customer newCustomer = new Customer(maKH, tenKH, sdt);
        customerController.addCustomer(newCustomer);
        clearInputFields();
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        String maKH = jtxtMaKH.getText();
        String tenKH = jtxtTenKH.getText();
        String sdt = jtxtSdt.getText();

        Customer updatedCustomer = new Customer(maKH, tenKH, sdt);
        customerController.updateCustomer(updatedCustomer);
        clearInputFields();
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        String maKH = jtxtMaKH.getText();
        if (maKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng cần xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa khách hàng này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            customerController.deleteCustomer(maKH);
            clearInputFields();
        }
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimActionPerformed
        String tenKH = jtxtTimKH.getText();
        customerController.searchCustomers(tenKH);
    }//GEN-LAST:event_jbtnTimActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainMenu_Manager2 managerFrame = new MainMenu_Manager2();
        managerFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jtxtTimKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTimKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTimKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JBottom;
    private javax.swing.JLabel JMaKH;
    private javax.swing.JPanel JMiddle;
    private javax.swing.JPanel JPanel_Top;
    private javax.swing.JLabel JTenKH;
    private javax.swing.JPanel JUpper;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Customers;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnTim;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTextField jtxtMaKH;
    private javax.swing.JTextField jtxtSdt;
    private javax.swing.JTextField jtxtTenKH;
    private javax.swing.JTextField jtxtTimKH;
    // End of variables declaration//GEN-END:variables
}
