/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MainMenuController;
import Model.Book;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import View.EmployeeM;
/**
 *
 * @author Admin
 */
public class MainMenu extends javax.swing.JFrame {
private MainMenuController controller;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        controller = new MainMenuController(this);
        controller.loadAndDisplayBooksByCategories();
    }
      public void populateCategoryTabs(LinkedHashMap<String, ArrayList<Book>> categorizedBooks) {
        jTabbedPaneBooks.removeAll(); // Clear all existing tabs

        if (categorizedBooks.isEmpty()) {
            jTabbedPaneBooks.addTab("Không có Danh mục", new JLabel("Không tìm thấy danh mục hoặc không có sách."));
            return;
        }

        for (Map.Entry<String, ArrayList<Book>> entry : categorizedBooks.entrySet()) {
            String categoryName = entry.getKey();
            ArrayList<Book> booksInCategory = entry.getValue();

            JPanel categoryPanel = new JPanel();
            categoryPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10)); // 10px spacing

            if (booksInCategory.isEmpty()) {
                categoryPanel.add(new JLabel("Không có sách trong danh mục này."));
            } else {
                for (Book book : booksInCategory) {
                    // Create an instance of the designed BookItemPanel
                    BookItemPanel bookItemPanel = new BookItemPanel();
                    bookItemPanel.setBook(book); // Assign book data to the panel
                    categoryPanel.add(bookItemPanel);
                }
            }
            // Place the category panel in a JScrollPane for scrolling if many books
            JScrollPane categoryScrollPane = new JScrollPane(categoryPanel);
            jTabbedPaneBooks.addTab(categoryName, categoryScrollPane);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMain = new javax.swing.JPanel();
        jLeft = new javax.swing.JPanel();
        jBanner = new javax.swing.JPanel();
        jbtnQli = new javax.swing.JButton();
        jMiddle = new javax.swing.JPanel();
        jTabbedPaneBooks = new javax.swing.JTabbedPane();
        jMiddle3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtxtTenSach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jspnSL = new javax.swing.JSpinner();
        jbtnAddHD = new javax.swing.JButton();
        jBottom = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtTenSachTK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtTenTacGiaTK = new javax.swing.JTextField();
        jbtnTim = new javax.swing.JButton();
        jRight = new javax.swing.JPanel();
        jBanner2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jUnder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTotalPd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTotalM = new javax.swing.JLabel();
        jbtnTT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtKHVIP = new javax.swing.JTextField();
        jbtnCheckKH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtGG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBanner.setBackground(new java.awt.Color(0, 0, 102));

        jbtnQli.setBackground(new java.awt.Color(0, 0, 102));
        jbtnQli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnQli.setForeground(new java.awt.Color(255, 255, 255));
        jbtnQli.setText("Quản lí");
        jbtnQli.setBorder(null);
        jbtnQli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBannerLayout = new javax.swing.GroupLayout(jBanner);
        jBanner.setLayout(jBannerLayout);
        jBannerLayout.setHorizontalGroup(
            jBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnQli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBannerLayout.setVerticalGroup(
            jBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBannerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbtnQli)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMiddleLayout = new javax.swing.GroupLayout(jMiddle);
        jMiddle.setLayout(jMiddleLayout);
        jMiddleLayout.setHorizontalGroup(
            jMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneBooks)
        );
        jMiddleLayout.setVerticalGroup(
            jMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        jMiddle3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Tên sách:");

        jLabel7.setText("Số lượng:");

        jbtnAddHD.setText("Thêm vào hóa đơn");

        javax.swing.GroupLayout jMiddle3Layout = new javax.swing.GroupLayout(jMiddle3);
        jMiddle3.setLayout(jMiddle3Layout);
        jMiddle3Layout.setHorizontalGroup(
            jMiddle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMiddle3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspnSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbtnAddHD)
                .addContainerGap())
        );
        jMiddle3Layout.setVerticalGroup(
            jMiddle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMiddle3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMiddle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jspnSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAddHD))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jBottom.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Tên sách:");

        jLabel9.setText("Tìm theo tên sách và tác giả");

        jLabel10.setText("Tên tác giả:");

        jbtnTim.setBackground(new java.awt.Color(204, 204, 204));
        jbtnTim.setText("Tìm");

        javax.swing.GroupLayout jBottomLayout = new javax.swing.GroupLayout(jBottom);
        jBottom.setLayout(jBottomLayout);
        jBottomLayout.setHorizontalGroup(
            jBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBottomLayout.createSequentialGroup()
                .addGroup(jBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBottomLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnTim))
                    .addGroup(jBottomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTenSachTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTenTacGiaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jBottomLayout.setVerticalGroup(
            jBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jbtnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtTenSachTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtTenTacGiaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jLeftLayout = new javax.swing.GroupLayout(jLeft);
        jLeft.setLayout(jLeftLayout);
        jLeftLayout.setHorizontalGroup(
            jLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMiddle3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLeftLayout.setVerticalGroup(
            jLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftLayout.createSequentialGroup()
                .addComponent(jBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMiddle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBanner2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hóa đơn");

        javax.swing.GroupLayout jBanner2Layout = new javax.swing.GroupLayout(jBanner2);
        jBanner2.setLayout(jBanner2Layout);
        jBanner2Layout.setHorizontalGroup(
            jBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBanner2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBanner2Layout.setVerticalGroup(
            jBanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBanner2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jList.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jListLayout = new javax.swing.GroupLayout(jList);
        jList.setLayout(jListLayout);
        jListLayout.setHorizontalGroup(
            jListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jListLayout.setVerticalGroup(
            jListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jUnder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tổng sản phẩm:");

        jTotalPd.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tổng tiền:");

        jTotalM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTotalM.setText("$1000");

        jbtnTT.setBackground(new java.awt.Color(102, 153, 255));
        jbtnTT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTT.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTT.setText("Thanh toán");

        jLabel4.setText("Khách hàng VIP:");

        jbtnCheckKH.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCheckKH.setText("Check");

        jLabel5.setText("Giảm giá:");

        jtxtGG.setText("0%");

        javax.swing.GroupLayout jUnderLayout = new javax.swing.GroupLayout(jUnder);
        jUnder.setLayout(jUnderLayout);
        jUnderLayout.setHorizontalGroup(
            jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUnderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jUnderLayout.createSequentialGroup()
                        .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTotalPd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtGG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jUnderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jUnderLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jtxtKHVIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnCheckKH))
                            .addGroup(jUnderLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTotalM, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnTT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jUnderLayout.setVerticalGroup(
            jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUnderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTotalPd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtxtGG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtKHVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCheckKH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jUnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTotalM))
                    .addComponent(jbtnTT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jRightLayout = new javax.swing.GroupLayout(jRight);
        jRight.setLayout(jRightLayout);
        jRightLayout.setHorizontalGroup(
            jRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBanner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jUnder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jRightLayout.setVerticalGroup(
            jRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRightLayout.createSequentialGroup()
                .addComponent(jBanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUnder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jMainLayout = new javax.swing.GroupLayout(jMain);
        jMain.setLayout(jMainLayout);
        jMainLayout.setHorizontalGroup(
            jMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainLayout.createSequentialGroup()
                .addComponent(jLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainLayout.setVerticalGroup(
            jMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnQliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQliActionPerformed
        MainMenu_Manager managerFrame = new MainMenu_Manager();
        managerFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnQliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBanner;
    private javax.swing.JPanel jBanner2;
    private javax.swing.JPanel jBottom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLeft;
    private javax.swing.JPanel jList;
    private javax.swing.JPanel jMain;
    private javax.swing.JPanel jMiddle;
    private javax.swing.JPanel jMiddle3;
    private javax.swing.JPanel jRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneBooks;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTotalM;
    private javax.swing.JLabel jTotalPd;
    private javax.swing.JPanel jUnder;
    private javax.swing.JButton jbtnAddHD;
    private javax.swing.JButton jbtnCheckKH;
    private javax.swing.JButton jbtnQli;
    private javax.swing.JButton jbtnTT;
    private javax.swing.JButton jbtnTim;
    private javax.swing.JSpinner jspnSL;
    private javax.swing.JLabel jtxtGG;
    private javax.swing.JTextField jtxtKHVIP;
    private javax.swing.JTextField jtxtTenSach;
    private javax.swing.JTextField jtxtTenSachTK;
    private javax.swing.JTextField jtxtTenTacGiaTK;
    // End of variables declaration//GEN-END:variables
}
