/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ODController;
import Controller.OrderController;
import Model.Book;
import Model.OD;
import Model.Order;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class OrderM extends javax.swing.JFrame {
    private OrderController orderController;
    private ODController odController;
    private MainMenu mainmenu;
    // Lưu đường dẫn ảnh hiện tại
    /**
     * Creates new form BookM
     */
    public OrderM() {
        initComponents();
        setLocationRelativeTo(null); 
        orderController = new OrderController(this, mainmenu);

        jtblOrder.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && jtblOrder.getSelectedRow() != -1) {
                    displaySelectedDH();
                    orderController.loadAllOD(jtxtMaDH.getText());
                }
            }
        });
        orderController.loadAllOrders();
    }
    
public void displayOrder(ArrayList<Order> orders) {
        DefaultTableModel dtm = (DefaultTableModel) jtblOrder.getModel();
        dtm.setRowCount(0); // Xóa dữ liệu cũ
        dtm.setColumnCount(0); // Xóa cột cũ

        // Định nghĩa cột (nếu chưa có trong initComponents hoặc muốn reset)
        dtm.addColumn("Mã đơn hàng");
        dtm.addColumn("Tên khách hàng");
        dtm.addColumn("Ngày bán");
        dtm.addColumn("Tổng tiền");
        dtm.addColumn("Nhân viên");
        for (Order order : orders) {
            Vector<Object> row = new Vector<>();
            row.add(order.getMaDH());
            row.add(order.getTenKH());
            row.add(order.getNgayBan());
            row.add(order.getTongTien());
            row.add(order.getTenNV());

            dtm.addRow(row);
        }
    }
public void displayOD(ArrayList<OD> ods) {
        DefaultTableModel dtm = (DefaultTableModel) jtblOD.getModel();
        dtm.setRowCount(0); // Xóa dữ liệu cũ
        dtm.setColumnCount(0); // Xóa cột cũ

        // Định nghĩa cột (nếu chưa có trong initComponents hoặc muốn reset)
        dtm.addColumn("ID");
        dtm.addColumn("Tên sản phẩm");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Đơn giá");
        dtm.addColumn("Tổng tiền sản phẩm");

        dtm.addColumn("Mã đơn hàng");

        for (OD od : ods) {
            Vector<Object> row = new Vector<>();
            row.add(od.getId());
            row.add(od.getTenSP());
            row.add(od.getSoLuong());
            row.add(od.getDonGia());
            row.add(od.getTongTien());
            row.add(od.getMaDH());

            dtm.addRow(row);
        }
    }
private void displaySelectedDH() {
    int selectedRow = jtblOrder.getSelectedRow();
    if (selectedRow >= 0) {
        DefaultTableModel model = (DefaultTableModel) jtblOrder.getModel();

        jtxtMaDH.setText(model.getValueAt(selectedRow, 0).toString());

        Object tenKHObj = model.getValueAt(selectedRow, 1);
        jtxtTenKH.setText(tenKHObj == null ? "" : tenKHObj.toString());
        
        jtxtNgayBan.setText(model.getValueAt(selectedRow, 2).toString());
        jtxtTongTien.setText(model.getValueAt(selectedRow, 3).toString());
                jtxtTenNV.setText(model.getValueAt(selectedRow, 4).toString());

    }
}


  public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    public void clearInputFields() {
        jtxtMaDH.setText("");
        jtxtTenKH.setText("");
        jtxtNgayBan.setText("");
        jtxtTongTien.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JUpper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnXoa = new javax.swing.JButton();
        jbtnNE = new javax.swing.JButton();
        jbtnXE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblOD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtMaDH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtNgayBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtTenNV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JUpper.setBackground(new java.awt.Color(0, 0, 102));
        JUpper.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lí đơn hàng");

        jbtnXoa.setBackground(new java.awt.Color(254, 255, 255));
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnNE.setBackground(new java.awt.Color(254, 255, 255));
        jbtnNE.setText("Nhập Excel");
        jbtnNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNEActionPerformed(evt);
            }
        });

        jbtnXE.setBackground(new java.awt.Color(254, 255, 255));
        jbtnXE.setText("Xuất Excel");
        jbtnXE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JUpperLayout = new javax.swing.GroupLayout(JUpper);
        JUpper.setLayout(JUpperLayout);
        JUpperLayout.setHorizontalGroup(
            JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JUpperLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnNE)
                .addGap(42, 42, 42)
                .addComponent(jbtnXE)
                .addGap(31, 31, 31)
                .addComponent(jbtnXoa)
                .addGap(10, 10, 10))
        );
        JUpperLayout.setVerticalGroup(
            JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JUpperLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JUpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnXoa)
                        .addComponent(jbtnNE)
                        .addComponent(jbtnXE))
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jtblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblOrder);

        jtblOD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblOD);

        jLabel2.setText("Mã đơn hàng");

        jtxtMaDH.setEditable(false);

        jLabel3.setText("Tên KH");

        jtxtTenKH.setEditable(false);

        jLabel4.setText("Ngày bán");

        jtxtNgayBan.setEditable(false);

        jLabel5.setText("Tổng tiền");

        jtxtTongTien.setEditable(false);

        jLabel6.setText("Tên nhân viên");

        jtxtTenNV.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JUpper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jtxtMaDH)
                            .addComponent(jtxtTenNV))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtTongTien)))
                        .addContainerGap(140, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        // TODO add your handling code here:
        String maDH = jtxtMaDH.getText(); // Lấy mã sách từ trường nhập
        if (maDH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn hàng cần xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa đơn hàng này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            orderController.deleteOrder(maDH);
        }
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNEActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(null);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        orderController.nhapExcel(file);
    }
    }//GEN-LAST:event_jbtnNEActionPerformed

    private void jbtnXEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXEActionPerformed
        // TODO add your handling code here:
        orderController.exportDonHangToExcel();
    }//GEN-LAST:event_jbtnXEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JUpper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnNE;
    private javax.swing.JButton jbtnXE;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTable jtblOD;
    private javax.swing.JTable jtblOrder;
    private javax.swing.JTextField jtxtMaDH;
    private javax.swing.JTextField jtxtNgayBan;
    private javax.swing.JTextField jtxtTenKH;
    private javax.swing.JTextField jtxtTenNV;
    private javax.swing.JTextField jtxtTongTien;
    // End of variables declaration//GEN-END:variables
}
